In [5]:
import numpy as np

In [6]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [13]:
array = np.random.randint(1, 10, (3, 4))
print(array)

[[8 7 8 3]
 [5 1 7 2]
 [2 4 4 2]]


In [15]:
print(array.ndim)
array.shape

2


(3, 4)

In [20]:
array.reshape((2, 6), order='C')

TypeError: 'tuple' object cannot be interpreted as an integer